#!/usr/bin/python
"""
Copyright (C) 2014-2017 cloudover.io ltd.
This file is part of the CloudOver.org project

Licensee holding a valid commercial license for this software may
use it in accordance with the terms of the license agreement
between cloudover.io ltd. and the licensee.

Alternatively you may use this software under following terms of
GNU Affero GPL v3 license:

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version. For details contact
with the cloudover.io company: https://cloudover.io/


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.


You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import syslog
import traceback
import django
import sys
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "corenode.settings")
django.setup()

from corenetwork.driver_interface import DriverInterface

drivers = DriverInterface.get_all_drivers()

def print_help():
    print "Usage: %s [configure|start|stop]" % sys.argv[0]

if __name__ == "__main__":
    try:
        if len(sys.argv) < 2:
            print_help()
        elif sys.argv[1] == 'configure':
            for driver in drivers:
                driver.configure_node()
        elif sys.argv[1] == 'start':
            for driver in drivers:
                driver.startup_node()
        elif sys.argv[1] == 'stop':
            for driver in drivers:
                driver.shutdown_node()
        else:
            DriverInterface.get_core_driver().cli_handle(sys.argv)
    except Exception as e:
        syslog.syslog(syslog.LOG_CRIT, "cc-node: action %s failed: %s" % (sys.argv[1], str(e)))
        stack = traceback.format_exc().splitlines()
        for line in stack:
            syslog.syslog(syslog.LOG_CRIT, line)
